// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

#include "../ShaderHelpers.hlsl"

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer <float3> Result;
float2 _Seed;
float3 _Normal;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    Result[id.x] = RandomPointOnHemisphere(id, _Normal, _Seed, 5);
}
