// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Main

#include "../ShaderHelpers.hlsl"


StructuredBuffer<float> _inputDataA;
StructuredBuffer<float> _inputDataB;
RWStructuredBuffer<float> _outputData;


int _Cols;
int _Transpose; //0 = none, 1 = A, 2 = B, 3 = both.

[numthreads(8,8,8)]
void Main (uint3 id : SV_DispatchThreadID)
{
	MatrixMultiply(id, _Cols, _inputDataA, _inputDataB, _outputData, _Transpose);
}